### ISSUE TITLE
Implementation of the thermometer

### ISSUE THREAD

**Issue by AddH1008** [kofigyan/Thermometer#1]
Hi Kofi!

Your work is very interesting!
I added your thermometer in my project where i'm doing a monitoring app for a vehicle. 
My issue is that I imported your widget, then used it in a relative layout, but I dont know how to modify it to display a temperature value from my MainActivity.

Could you give me an advice on how to do that? 
I am not so experienced and thus cannot figure it out alone.
Thanks a lot!

**Comment by kofigyan** [comment]
Hello AddH1008,
   Thank you for the feedback and also glad you found my work useful. 
If not late for you,l will update the work over the weekend if not tomorrow, to measure real time temperature(ambient).Currently consulting on some apps hence making it difficult to update immediately.
- Kofi Gyan
  Senior Android Engineer
  Jans Lab
  email : kofigyan2011@gmail.com

**Comment by kofigyan** [comment]
Hello AddH1008,
   Thank you for the feedback and also glad you found my work useful.
If not late for you,l will update the work over the weekend if not
tomorrow, to measure real time temperature(ambient).Currently consulting on
some apps hence making it difficult to update immediately.
- Kofi Gyan
  Senior Android Engineer
  Jans Lab
  email : kofigyan2011@gmail.com

**Comment by AddH1008** [comment]
Thats great news!

I’m sure other people will also be happy to just import it as a module and do a setTemp().
I let it as a dummy temperature display for the moment and really look forward for your update!

Kind regards

Adrien

**Comment by AddH1008** [comment]
Hi Kofi,

Did you have time to work on the issue?

I don’t wan’t to stress you but just show you my interest ;)

Thanks a lot!

**Comment by kofigyan** [comment]
Hello AddH1008,
    Sorry for the delay. I have actually worked on it. The issue is with
testing. I have so far tested with about 10 devices about 8 Samsung devices
and Htc but none have support for ambient temperature sensing which is what
we are trying to read. Most have support for sensing light,pressure etc.
But my little research tells me there some few devices(Htc examples) with
support for ambient temperature (ambient sensor).
      If you have a device with an ambient temperature sensor then l will
try and round up tomorrow for you to do the testing.
- Kofi

**Comment by AddH1008** [comment]
Sounds interesting!

In my case I want to use it for a e-vehicle HMI. The sensor will be a digital sensor connected to a Raspberry Pi and the communication is via wifi for the moment.

My phone is a Xperia Z1C so not possible for testing but you can’t you simply fake the temperature from the main activity?

Best regards

**Comment by kofigyan** [comment]
Ok will run the test with the other sensors. I am about 99 percent sure
with that test working you can equally run it on your device successfully.
     Let give you a feedback tomorrow on the test.
- Kofi.

**Comment by kofigyan** [comment]
Hello AddH1008,
-   Project updated to measure ambient temperature. Check this in the
  Thermometer class. Other two classes(DummyThermometer and LightSensorMeter)
  are just for testing. *
  Try it and let me know if it useful in helping you solve the problem. The
  next update will be fine tuning it and then working on calibrating the
  thermometer.
- Kofi.

**Comment by AddH1008** [comment]
I have a little issue on my Xperia Z, the LUX value appear ni the log but is not changing on the screen and neither sending toast.

However thats great, I will now be able to modify it more easily to implement it in my app.

Thanks a lot!
